# Docker Compose configuration for E-commerce Application

version: '3.8'

services:
  # Main Flask Application
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - SECRET_KEY=change-this-in-production
      - DATABASE_URL=sqlite:///ecommerce.db
    volumes:
      - ./static/uploads:/app/static/uploads
      - ./instance:/app/instance
      - ./logs:/app/logs
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - ecommerce-network

  # PostgreSQL Database (Optional - for production)
  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_DB=ecommerce
      - POSTGRES_USER=ecommerce_user
      - POSTGRES_PASSWORD=ecommerce_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - ecommerce-network

  # Redis for Session Storage (Optional)
  redis:
    image: redis:6-alpine
    ports:
      - "6379:6379"
    restart: unless-stopped
    networks:
      - ecommerce-network

  # Nginx Reverse Proxy (Optional - for production)
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./static:/app/static
    depends_on:
      - web
    restart: unless-stopped
    networks:
      - ecommerce-network

volumes:
  postgres_data:

networks:
  ecommerce-network:
    driver: bridge